server:
  port: 8950
spring:
  application:
    name: biz-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-alpha:8900/eureka/,http://eureka-beta:8901/eureka/,http://eureka-charlie:8900/eureka/
#      defaultZone: http://eureka-alpha:8900/eureka/