server:
  port: 7900
# 应用名称
spring:
  application:
    name: second-kill
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second-kil?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root1234
  redis:
    host: localhost
mybatis:
  configuration:
    map-underscore-to-camel-case: true