server:
  port: 7712
# 应用名称
spring:
  application:
    name:  rocketmq-springboot
rocketmq:
  name-server: localhost:9876
  producer:
    group: springboot_group
# 消息标识
mq:
  test:
    topic: springboot_topic
    consumer:
      group: springboot_topic_group